Use ipython-sql from conda
Avoid build error:

```
Collecting prettytable (from ipython-sql==0.3.9->-r /home/jovyan/binder/condaenv.2muu0otf.requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/ef/30/4b0746848746ed5941f052479e7c23d2b56d174b82f4fd34a25e389831f5/prettytable-0.7.2.tar.bz2
    Error [Errno 22] Invalid argument: '/srv/conda/bin/python' while executing command python setup.py egg_info
Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument: '/srv/conda/bin/python'

CondaValueError: pip returned an error
```